BEGIN;

-- 1. Eliminar las restricciones (FK) viejas
ALTER TABLE Servicio DROP CONSTRAINT IF EXISTS FK_SERVICIO_SEDE;
ALTER TABLE Edificacion DROP CONSTRAINT IF EXISTS FK_EDIFICACION_SEDE;
ALTER TABLE EspacioFisico DROP CONSTRAINT IF EXISTS FK_ESPACIO_EDIFICACION;
ALTER TABLE Recursos DROP CONSTRAINT IF EXISTS FK_RECURSOS_ESPACIOFISICO;
ALTER TABLE Ajusta DROP CONSTRAINT IF EXISTS FK_AJUSTA_SEDE;
ALTER TABLE Estacionamiento DROP CONSTRAINT IF EXISTS FK_ESTACIONAMIENTO_SEDE;
ALTER TABLE Puesto_Estacionamiento DROP CONSTRAINT IF EXISTS FK_PUESTO_ESTACIONAMIENTO;
ALTER TABLE Reserva DROP CONSTRAINT IF EXISTS FK_RESERVA_ESPACIO;
ALTER TABLE Reserva DROP CONSTRAINT IF EXISTS FK_RESERVA_PUESTO;

-- 2. Volver a crearlas pero agregando "ON UPDATE CASCADE"
ALTER TABLE Servicio ADD CONSTRAINT FK_SERVICIO_SEDE FOREIGN KEY (nombre_sede) REFERENCES Sede(nombre) ON UPDATE CASCADE;
ALTER TABLE Edificacion ADD CONSTRAINT FK_EDIFICACION_SEDE FOREIGN KEY (nombre_sede) REFERENCES Sede(nombre) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE EspacioFisico ADD CONSTRAINT FK_ESPACIO_EDIFICACION FOREIGN KEY (nombre_edif, direccion_exacta, nombre_sede) REFERENCES Edificacion(nombre, direccion_exacta, nombre_sede) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Recursos ADD CONSTRAINT FK_RECURSOS_ESPACIOFISICO FOREIGN KEY (numero, nombre_espacio_fisico, direccion_exacta, nombre_sede) REFERENCES EspacioFisico(numero, nombre_edif, direccion_exacta, nombre_sede) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Ajusta ADD CONSTRAINT FK_AJUSTA_SEDE FOREIGN KEY (nombre_sede) REFERENCES Sede(nombre) ON UPDATE CASCADE;
ALTER TABLE Estacionamiento ADD CONSTRAINT FK_ESTACIONAMIENTO_SEDE FOREIGN KEY (nombre_sede) REFERENCES Sede(nombre) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Puesto_Estacionamiento ADD CONSTRAINT FK_PUESTO_ESTACIONAMIENTO FOREIGN KEY (nombre_estacionamiento, nombre_sede) REFERENCES Estacionamiento(nombre, nombre_sede) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Reserva ADD CONSTRAINT FK_RESERVA_ESPACIO FOREIGN KEY (numero_espacio, nombre_edif, direccion_exacta, nombre_sede_espacio) REFERENCES EspacioFisico(numero, nombre_edif, direccion_exacta, nombre_sede) ON UPDATE CASCADE;
ALTER TABLE Reserva ADD CONSTRAINT FK_RESERVA_PUESTO FOREIGN KEY (numero_puesto, nombre_estacionamiento, nombre_sede_puesto) REFERENCES Puesto_Estacionamiento(numero, nombre_estacionamiento, nombre_sede) ON UPDATE CASCADE;

COMMIT;
